transform:
  enabled: true

  offset_x: 0.0
  offset_y: 0.0
  offset_z: 1.2

  invert_x: false
  invert_y: true
  invert_z: true

filter:
  enabled: true

  enable_x: true
  min_x: -10.0
  max_x:  10.0

  enable_y: true
  min_y: -10.0
  max_y:  10.0

  enable_z: true
  min_z:  0.15
  max_z:  1.50

  enable_radius: true
  min_radius: 0.5
